#Python For Matlab Users

###Author: Syed (Sadat) Nazrul

# 

####Matrix Manipulation

$$A = \left[ \begin{array}{ccc} 1 & 1 &1 \\ 2 & 4 & 5\\ 5 & 7 & 6\\ \end{array} \right]$$ 

In [42]:
import numpy as np

In [43]:
A = np.matrix('1,1,1 ; 2,4,5 ; 5,7,6')

print(A)

[[1 1 1]
 [2 4 5]
 [5 7 6]]


In [44]:
A = np.matrix([[1,1,1],[2,4,6],[5,7,6]])

print(A)

[[1 1 1]
 [2 4 6]
 [5 7 6]]


In [45]:
print(A[0,0])

1


In [46]:
print(A[:,0])

[[1]
 [2]
 [5]]


In [47]:
print( A[0,:])

[[1 1 1]]


In [48]:
A.shape

(3, 3)

####Math Functions

In [49]:
np.sum(A[0,:])

3

In [50]:
np.dot(A,A)

matrix([[ 8, 12, 13],
        [40, 60, 62],
        [49, 75, 83]])

In [51]:
np.cross(A,A)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

####Plotting

In [52]:
import matplotlib.pyplot as plt

In [53]:
plt.figure()
plt.plot(A[:,0])
plt.plot(A[:,1])
plt.title('Sample Matlab type Plot')
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.show()